travis:
  secure:
    BINSTAR_TOKEN: AKxdPq7akhmxFWD1/1b+cC33k8LG+j9yz0ZdKobgUVn9c4Dr/FWzzj/aftqvbxBtyn/J6dbDJTuix0M8XilLQJtlyfOPuh7ewe+YebW0uN++1IeV0gUXO6oypt4R3FTKL+1+xvZQlACg7vG7NphAXwbt812ajGrIdgNiTA/d2i04drB1KH6THE7EJ/+c9uZFD4NOro2/cP1hhcEOZkF046BpvhKhJKE6yF0iwN9iig8sji3kgfDYPnOCZUgBJIfbqfg+4fpsJzfzJm6cj9du0Mr94eNHxnR0Zq3da52kVNFae5qyZxHbUae8mP+3oOvI+sfLKb/bwklc2rhjtWAEbtRpuvzBdWlm/B4dPPDcoVRAAEK2veMz42Yjm3u4XWYdwh7XTVCIt3+EbPda6Yd2a1YrazbH/ujg9DirA9Uy+VYPupf9pFVIaNkRSjB3yMyniftcyKfVRi8OLn7h33Nu6+FYoo+sQ0tM9BOqRkzVOzLa2snLZenZPkvYcgGMD3i516XkqZHoqJHBj3G3juTkzFR7Uvel/1dSQ2Od7dHT8E0nAR4kEZTNFwLwpjVe3P7vtVm5NKLr+pqPdkJ5rlhosvs7KZgJdfeHzQIsePNK6TcJdmTp7EqMSMFjoeDudapS+Mv+V/GC76nDUMmlvoRjupHpAlUAAn7yQL8FeVYKtvs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
