travis:
  secure:
    BINSTAR_TOKEN: UB2REJaWiCLaR4eXb4QEKm9w3yYMarlPy+XLHzcHnUrf/93FLZCGPT+0JzBpu4O5wsBAuSJiQ6KlE94jrQOwI9autTJyyQexUN5QNbHdkWAO7YFJKZseD0vcJ1V3w3okjpZ28JympLQkGnpedF5Lm7LPwwh7hasL3UuIFNYqvVCA8JrsADczA07gYgJdL76Cw0VCRJP66VsUDBIlu9z150a6NIPc7btB9t7chor54af/TE+B1nBfWKOZ/gGih20v4VtKTttiZZ9AH6zKRdFefABL/TPkXt2So6cUv9h6VohQAx1FmPgsTxp+mMl2SxhvZhG6iJHcdN4mUmH9fiFoejcHpLKTvKrGD637mgtL9CaXe7vO3C7K/c/zvF8qGu5nMwSEgxeAQJr7wLNZWNPimhexxrG6JPNBmA/AJYw1vV9bpbZPuHjnmzuLMGQzhtjnDTbPh++W6Rd+W3SGJO+5OqCdeSsQ8IqIlNdtXVWW7AtNljZrCAudgvHu29vO+Y5QfzvERStN2DU+AwfERlK6KukQGpFwLOwAAit3ZGfRHPF7iZRMRpkoZsV2bZvSmoYQ3TsNumvFi2APAQ2SqDpueG9XFRRk/i2ld6ecZtJY05GKEgV25Upnm9y9HEljNHz29xgf+XrtE6fM5sxQxfA3SoS1eOvlw/oNjE2L8w2rTZY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
