travis:
  secure:
    BINSTAR_TOKEN: jv19zHu8qREZpBeXqAVL3ndzYbuBGGUqr3e0trq8ZssTSB3efViufzJtoNo5k37gAS2h126Z3Fl7+k1IJg2jo7XF/DqCVtFggV1mjHZ7DtLQpbqPumdRQT9ApSvozaM/vP0LFg8PiEmSGqvnoVifQNODUXaIBe54LX6xdTK/qXVPJY3VGY/t+w7ImXo+h4rPtyV+8itzv1WlAzO/FqO2QsFQgvNywWZNEutgj0m7GKwjYoY8qSVzsDhtuC/6k4SrRxNj0SZ4Sr5oCMEbHcxoL/N19Ai107gKacS18QYa+eioUHA7v25UTJyf3u//s8rpHZq8lrj9QJkTic1CeduErfdikTZ5iag3db/xgEC2ioiyqoj2I1Iypqw85Y0uZdymGKALf89e6s1pQ8HVVmNJ0/Ua8/fWUCjCjTURFPJnDwPSbMkHgtn+dHbuWKmlFE9eZwSCrgAa0PinXMIhun4WZ660xnG2zXMj/eQpCaZsojKV1a0RGsSnehiEnlPu2DkTVa/5oKuysEKwIEHI08KcVa+OXWaSZtlwNChT38xzCgTafY/DtgSL9wC/fxitkMTL1lP/8MaAdOcLYNDwTigS7mPIHxdTACiFVar/2JYcD5Z5Ye8JiQmfR5YJ5QgbYPo/WayByTRwD60Yju+RSRJY1s5ySP9KKXVd+l75qncu+LY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
